language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: 'mbogner-github'
    token:
      secure: 'fcf321fd035ce8b9cd5e3cb46a285d289141b5b6'
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
script:
  - ./gradlew check
  - ./gradlew jacocoTestReport
  - ./gradlew sonarqube
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'